# Generated by Django 4.1.6 on 2023-02-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('davlat', models.CharField(max_length=35)),
                ('logo', models.FileField(upload_to='')),
                ('president', models.CharField(max_length=35)),
                ('murabbiy', models.CharField(max_length=30)),
                ('yil', models.DateField()),
                ('eng_katta_herid', models.FloatField()),
                ('eng_katta_sotuv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HozirgiMavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavsum', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('pozitsiya', models.CharField(max_length=35)),
                ('millat', models.CharField(max_length=25)),
                ('tr_narx', models.FloatField()),
                ('tug_yil', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosi_app.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.FloatField()),
                ('tax_narxi', models.FloatField()),
                ('mavsum', models.CharField(max_length=30)),
                ('eski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotganlari', to='assosi_app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosi_app.player')),
                ('yangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosi_app.club')),
            ],
        ),
    ]
